module.exports = {
  apps: [{
    name: "bait-al-mandi",
    script: "node_modules/next/dist/bin/next",
    args: "start -H 0.0.0.0",
    cwd: __dirname,
    env: { NODE_ENV: "production", PORT: 3000 },
    instances: 1,
    exec_mode: "fork",
    watch: false,
    max_memory_restart: "500M",
    error_file: "logs/err.log",
    out_file: "logs/out.log",
    log_file: "logs/combined.log",
    time: true,
    autorestart: true,
    max_restarts: 10,
    restart_delay: 5000,
  }],
};
